phases:
  pre_build:
    command:
      - echo Install packages...
      - npm install
    build:
      command:
        - echo Create build...
        - npm run build
    post_build:
      command:
        - echo Removing unnecessary files...
        - rm -rf node_modules/
artifacts:
  base-directory: "."
  files:
    - "**/*"