version: "3.7"

services:
  db:
    restart: always
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - dev.env
    ports:
      - "3306:3306"
    networks:
      - backend

  api:
    build: 
      dockerfile: Dockerfile.dev
      context: .
    depends_on: 
      - db
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - dev.env
    networks:
      - backend

volumes: 
  db_data: {} 
networks: 
  backend: